version: 0.2

env:
  variables:
    key: "value"
        
phases:
  install:
    runtime-versions:
      java: corretto21
    
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew build

artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - scripts/**
  discard-paths: yes
  packaging: ZIP